version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'   # ← quote so YAML treats it as a string
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"                       # host↔container
    volumes:
      - /d/docker_volume/mysql-nishar-db:/var/lib/mysql    # 👈 Mount to Windows folder
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql    # 👈 SQL init script
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: nodeapp1
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=testdb
      - DB_PORT=3306
      - PORT=3000

# Removed the named volume since it's not used anymore
# volumes:
#   db_data:
